spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations

  data:
    redis:
      port: 3004

  ai:
    google:
      genai:
        api-key: NONE_FOR_TEST

auth:
  jwt:
    secret: 56868fddf022cfa637637cf5613d97b5
    expiration:
      milliseconds: 900000 # 15 mins
  verification:
    expirationInMinutes: 15
  disable-login-rate-limit: false

logging:
  level:
    org.springframework.security: DEBUG
    org.droid.zero.multitenantaipayrollsystem: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE