spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_DB}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations

  data:
    redis:
      port: 3004

  ai:
    google:
      genai:
        api-key: ${AI_GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash-lite
            temperature: 0.5

  security:
    user:
      name: user
      password: secret

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET}
    expiration:
      milliseconds: ${AUTH_JWT_EXPIRATION_MILLISECONDS}
  verification:
    expirationInMinutes: 15