spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  ai:
    google:
      genai:
        api-key: NONE_FOR_TEST

auth:
  jwt:
    secret: 56868fddf022cfa637637cf5613d97b5
    expiration:
      milliseconds: 900000 # 15 mins
  verification:
    expirationInMinutes: 15
